"""empty message

Revision ID: 40162fbab4d5
Revises: 665cbc0a530e
Create Date: 2024-01-19 16:18:21.918672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40162fbab4d5'
down_revision = '665cbc0a530e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
